package enums;

public enum FactionsEnum {
    TATARS, JAPANESE, CHINESE, KOREANS, MALIANS, SARACENS, FRANKS, BRITIONS, SCOTTISH, DANISH, RUSSIANS, TURKS, MORROCANS,
    KIPCHAKS, SCYTHIANS, LOMBARDS, SPANIARDS, GREEKS, CANADIANS, NORMANS, AZERIS, THAI
}
